spring:
  profiles:
    default: local
  application:
    name: backend-member

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:username}
    password: ${GMAIL_APP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET:jwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecret}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION:10000}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION:10000}
